# BlackMetal by metalelf0, https://github.com/metalelf0
# This schemes are available as open source under the terms of the [MIT License](https://opensource.org/licenses/MIT).

selection_foreground #000000
selection_background #ffffff

foreground #C2C2C2
background #333333

color0   #000000
color1   #5f8787
color2   #dd9999
color3   #a06666
color4   #888888
color5   #999999
color6   #aaaaaa
color7   #c1c1c1
color8   #0d0d0d
color9   #5f8787
color10  #dd9999
color11  #a06666
color12  #888888
color13  #999999
color14  #aaaaaa
color15  #c1c1c1

active_tab_foreground #eeeeee
active_tab_background #545454
inactive_tab_foreground #C2C2C2
inactive_tab_background #292929


active_border_color #ffffff
