# ---------------------------------------------------------
# KITTY CONFIGURATION
# Theme: Catppuccin-Frappe
# Font: GeistMono Nerd Font
# ---------------------------------------------------------

# --- Fonts ---
# BEGIN_KITTY_FONTS
font_family      family="GeistMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.5
# END_KITTY_FONTS

# --- Appearance ---
# BEGIN_KITTY_THEME
# Black Metal
include current-theme.conf
# END_KITTY_THEME

background_opacity 0.75
window_padding_width 30
confirm_os_window_close 0

# --- Cursor Customization ---
# Modern "Ghost" trail effect (Requires Kitty 0.35.0+)
cursor_trail                 1
cursor_trail_decay           0.1 0.4
cursor_trail_start_threshold 1
scrollback_lines	10000
scrollbar_interactive no
scrollbar_width 0

# --- Performance & Resizing ---
# These settings specifically help with Hyprland's tiling resizing
shell_integration      enabled

# --- Mouse Bindings ---
# Standard double/triple click selection behavior
mouse_map left doublepress ungrabbed mouse_selection word
mouse_map left triplepress ungrabbed mouse_selection line

# --- Keybindings ---
# Modern copy/paste (mimics standard Windows/Linux GUI behavior)
map ctrl+c copy_or_interrupt
map ctrl+v paste_from_clipboard


